spring:
  main:
    banner-mode: "off"
  application:
    name: aish
  shell:
    history:
      enabled: false
    interactive:
      enabled: true
  ai:
    provider: OLLAMA
    ollama:
      chat:
        options:
          model: deepseek-r1:1.5b
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

logging:
  level:
    root: WARN

shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED
